#! /bin/sh -e

case "$1" in
  configure)
    [ -x /usr/bin/update-menus ] && update-menus
  ;;

  abort-upgrade|abort-deconfigure|abort-remove)
    # how did we got here? Force a non-zero exit code
    exit 1
  ;;
  *)
    echo "postinst called with unkown argument: \$1" >&2
  ;;
esac

exit 0
